baseURL = "http://drademacher.de/"
title = "Danny Rademacher"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "About Me And Things I Do"
description = ""
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false


  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/drademacher"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/drademacher"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true
