baseURL = "http://drademacher.de/"
languageCode = "en-us"
title = "Danny Rademacher"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Danny Rademacher"
    description = "About Me And Things I Do"
    githubUsername = "drademacher"
    accent = "#612e10"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "rust"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/projects"
    name = "Projects"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:danny.rademacher@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/drademacher"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/drademacher"
    name = "fab fa-linkedin"
    weight = 3
